apiVersion: kubeagents.x-k8s.io/v1alpha1
kind: OperatorAgent
metadata:
  name: operator-agent-ac-3-us-central1
  namespace: kubeagents-system
spec:
  harness:
    clusterName: "ac-3"
    location: "us-central1"
    projectId: "kube-agents-gke"
    hermes:
      apiServerSecretRef:
        name: "platform-agent-secrets"
        key: "API_SERVER_KEY"
  deployment:
    image: "us-central1-docker.pkg.dev/kube-agents-gke/kubeagents-operator-repo/operator-agent"
    tag: "latest"
    imagePullPolicy: Always
  security:
    serviceAccountName: "operator-agent-ac-3"
    serviceAccountAnnotations:
      iam.gke.io/gcp-service-account: "op-gsa-ac-3@kube-agents-gke.iam.gserviceaccount.com"
    remoteIdentitySubject: "op-gsa-ac-3@kube-agents-gke.iam.gserviceaccount.com"
