#!/usr/bin/env bash
# Formats and logs deployment configuration summary for CI runs.
set -euo pipefail

echo "======================================================================"
echo "🚀 RELEASE CANDIDATE DEPLOYMENT CONFIGURATION"
echo "======================================================================"
echo "Target Project ID:          ${GCP_PROJECT_ID:-<NOT SET IN ENVIRONMENT>}"
echo "Target Project Number:      ${GCP_PROJECT_NUMBER:-<NOT SET IN ENVIRONMENT>}"
echo "Target GCP Region:          ${GCP_REGION:-<NOT SET IN ENVIRONMENT>}"
echo "Target Cluster Name:        ${GKE_CLUSTER_NAME:-<NOT SET IN ENVIRONMENT>}"
echo "Service Account:            ${GCP_SERVICE_ACCOUNT:-<NOT SET IN ENVIRONMENT>}"
echo "----------------------------------------------------------------------"
echo "Release Tag:                ${RC_TAG:-<NOT SET>}"
echo "Candidate Commit SHA:       ${COMMIT_SHA:-<NOT SET>}"
echo "Candidate Image Tag:        ${IMAGE_TAG:-<NOT SET>}"
echo "----------------------------------------------------------------------"
echo "Google Chat Enabled:        ${GOOGLE_CHAT_ENABLED:-<NOT SET>}"
echo "Google Chat Mode:           ${GOOGLE_CHAT_MODE:-<NOT SET>}"
echo "Google Chat Topic Name:     ${CHAT_TOPIC_NAME:-<NOT SET>}"
echo "----------------------------------------------------------------------"
echo "Model Provider:             ${MODEL_PROVIDER:-<NOT SET>}"
echo "Model Default Name:         ${MODEL_DEFAULT_NAME:-<NOT SET>}"
echo "Enable gVisor Isolation:    ${ENABLE_GVISOR:-<NOT SET>}"
echo "Agent K8s Permission Set:   ${PLATFORM_AGENT_PERMISSION_SET:-<NOT SET>}"
echo "Memory Enabled:             ${MEMORY_ENABLED:-<NOT SET>}"
echo "Memory Provider:            ${MEMORY_PROVIDER:-<NOT SET>}"
echo "User Profile Enabled:       ${USER_PROFILE_ENABLED:-<NOT SET>}"
echo "======================================================================"
