apiVersion: kubeagents.x-k8s.io/v1alpha1
kind: PlatformAgent
metadata:
  name: platform-agent
  namespace: agent-system
spec:
  harness:
    clusterName: "platform-agent-host"
    location: "us-east4"
    hermes:
      dashboardEnabled: true
      pluginsDebug: false
      platformAgentHome: "/opt/data"
      apiServerSecretRef:
        name: platform-agent-secrets
        key: API_SERVER_KEY
  deployment:
    image: "ghcr.io/gke-agentic/kube-agents/platform-agent-operator:sha-b0ca642"
    tag: "latest"
    imagePullPolicy: Always
  security:
    serviceAccountName: "platform-agent-platform-sa"
    workloadIdentity:
      gcp:
        gsaName: "platform-agent-bot"
        projectId: "mplakhtiy-gke-dev"
  model:
    provider: "gemini"
    default: "gemini-3.1-flash-lite"
    gemini:
      apiKeySecretRef:
        name: platform-agent-secrets
        key: GEMINI_API_KEY
  integration:
    googleChat:
      enabled: true
      projectId: "mplakhtiy-gke-dev"
      topicName: "platform-agent-chat-events"
      subscriptionName: "platform-agent-chat-events-sub"
      allowedUsers:
        - "mplakhtiy@google.com"
      homeChannel: ""
