#!/usr/bin/env python3
"""Generates or checks charts/kube-agents/files/footprint.yaml from an operator golden (#749).

The chart's quota preflight cannot render the operator's pods, so it needs their resource
totals as data. This sums them from the operator's golden manifest for the default example
CR and writes them to a file the chart reads with `.Files.Get`.

The source is a golden, not a live render and not k8s-operator/config/, so changing the
operator's resources takes two steps in order: re-bless the golden
(cd k8s-operator && go test ./internal/controller/... -update), then `make chart-sync`.
Syncing first regenerates the old numbers from the stale golden.

Verified in CI by `make chart-check`, which runs this with --check.
"""

import argparse
import pathlib
import sys

import yaml

_ROOT = pathlib.Path(__file__).resolve().parents[1]
_GOLDEN_MANIFEST = (
    _ROOT
    / "k8s-operator"
    / "internal"
    / "testing"
    / "testdata"
    / "platform"
    / "expected"
    / "platformagent.yaml"
)
_FOOTPRINT_FILE = _ROOT / "charts" / "kube-agents" / "files" / "footprint.yaml"

_HEADER = (
    "# GENERATED by `make chart-sync` — do not edit.\n"
    "# Summed from the operator's golden manifest for the default example CR\n"
    "# (k8s-operator/internal/testing/testdata/platform/expected/platformagent.yaml),\n"
    "# not from a live render. Re-bless that golden before syncing, or this regenerates\n"
    "# the old numbers. See hack/sync-chart-manifests.sh.\n"
)

# Workload and container names in the golden. The generator finds these by name, so a
# rename in the operator surfaces here as a "not found in the golden" error rather than
# as a silently-zero footprint.
_SHELL_WORKLOAD = "platformagent-shell"
_SHELL_CONTAINER = "shell"
_CRED_PROXY_WORKLOAD = "platformagent-credential-proxy"
_CRED_PROXY_CONTAINER = "envoy-credential-proxy"
_GATEWAY_WORKLOAD = "platformagent-gateway"
_AGENT_CONTAINER = "platform-agent"
_DASHBOARD_CONTAINER = "platform-agent-dashboard"
_FLUENT_BIT_CONTAINER = "fluent-bit"
_AGENT_API_AUTH_CONTAINER = "agent-api-auth"

_KIND_STATEFULSET = "StatefulSet"
_KIND_DEPLOYMENT = "Deployment"
_KIND_PVC = "PersistentVolumeClaim"

_REQUESTS = "requests"
_LIMITS = "limits"
_CPU = "cpu"
_MEMORY = "memory"
_EPHEMERAL_STORAGE = "ephemeral-storage"
_STORAGE = "storage"

_MIB = 1024**2
_GIB = 1024**3
_MILLICORES_PER_CORE = 1000
_ZERO_QUANTITY = "0"

# `make chart-check` distinguishes these: 1 means the committed file has drifted and the
# fix is to re-sync, anything else means the check could not run and the fix is different.
_EXIT_DRIFT = 1
_EXIT_CANNOT_RUN = 2

_BINARY_SI_UNITS = {
    "Ki": 1024,
    "Mi": _MIB,
    "Gi": _GIB,
    "Ti": 1024**4,
    "Pi": 1024**5,
    "Ei": 1024**6,
}

_DECIMAL_SI_UNITS = {
    "k": 1000,
    "M": 1000**2,
    "G": 1000**3,
    "T": 1000**4,
    "P": 1000**5,
    "E": 1000**6,
}


def parse_bytes(val: str | int | float) -> int:
    """Parse a Kubernetes memory/storage quantity to integer bytes."""
    if isinstance(val, (int, float)):
        return int(val)
    val = str(val).strip()
    if not val:
        return 0
    for unit, mult in _BINARY_SI_UNITS.items():
        if val.endswith(unit):
            return int(float(val[: -len(unit)]) * mult)
    for unit, mult in _DECIMAL_SI_UNITS.items():
        if val.endswith(unit):
            return int(float(val[: -len(unit)]) * mult)
    return int(val)


def parse_cpu_millis(val: str | int | float) -> int:
    """Parse a Kubernetes CPU quantity to integer millicores."""
    if isinstance(val, (int, float)):
        return int(float(val) * _MILLICORES_PER_CORE)
    val = str(val).strip()
    if not val:
        return 0
    if val.endswith("m"):
        return int(val[:-1])
    return int(float(val) * _MILLICORES_PER_CORE)


def format_cpu(millis: int) -> str:
    """Render millicores the way kube-agents.formatCpu does, so the two agree."""
    if millis and millis % _MILLICORES_PER_CORE == 0:
        return str(millis // _MILLICORES_PER_CORE)
    return f"{millis}m"


def format_bytes(num_bytes: int) -> str:
    """Render bytes the way kube-agents.formatBytes does, so the two agree."""
    if num_bytes and num_bytes % _GIB == 0:
        return f"{num_bytes // _GIB}Gi"
    if num_bytes and num_bytes % _MIB == 0:
        return f"{num_bytes // _MIB}Mi"
    return str(num_bytes)


def _quantity(container: dict, section: str, key: str, parse) -> int:
    resources = container.get("resources") or {}
    return parse((resources.get(section) or {}).get(key, _ZERO_QUANTITY))


def _sum_quantity(containers: list, section: str, key: str, parse) -> int:
    return sum(_quantity(c, section, key, parse) for c in containers)


def _workload_entry(containers: list, pods: int) -> dict:
    """Sum a set of co-scheduled containers into one footprint entry.

    Init containers are deliberately excluded. A pod's effective request is the greater of
    (largest init container, sum of regular and sidecar containers), and for every workload
    here the sum dominates, so adding the init containers would over-count.
    """
    req_cpu = _sum_quantity(containers, _REQUESTS, _CPU, parse_cpu_millis)
    lim_cpu = _sum_quantity(containers, _LIMITS, _CPU, parse_cpu_millis)
    req_mem = _sum_quantity(containers, _REQUESTS, _MEMORY, parse_bytes)
    lim_mem = _sum_quantity(containers, _LIMITS, _MEMORY, parse_bytes)
    req_eph = _sum_quantity(containers, _REQUESTS, _EPHEMERAL_STORAGE, parse_bytes)
    lim_eph = _sum_quantity(containers, _LIMITS, _EPHEMERAL_STORAGE, parse_bytes)

    return {
        _REQUESTS: {
            _CPU: format_cpu(req_cpu),
            _MEMORY: format_bytes(req_mem),
            _EPHEMERAL_STORAGE: format_bytes(req_eph),
        },
        _LIMITS: {
            _CPU: format_cpu(lim_cpu),
            _MEMORY: format_bytes(lim_mem),
            _EPHEMERAL_STORAGE: format_bytes(lim_eph),
        },
        "cpuMillisRequest": req_cpu,
        "cpuMillisLimit": lim_cpu,
        "memoryBytesRequest": req_mem,
        "memoryBytesLimit": lim_mem,
        "ephemeralStorageBytesRequest": req_eph,
        "ephemeralStorageBytesLimit": lim_eph,
        "pods": pods,
    }


def _pod_spec(doc: dict) -> dict:
    return ((doc.get("spec") or {}).get("template") or {}).get("spec") or {}


def _claim_storage(claim: dict) -> int:
    resources = (claim.get("spec") or {}).get("resources") or {}
    return parse_bytes((resources.get(_REQUESTS) or {}).get(_STORAGE, _ZERO_QUANTITY))


def extract_footprint() -> dict:
    """Extract operator-rendered resource requirements from the golden manifest."""
    if not _GOLDEN_MANIFEST.is_file():
        raise FileNotFoundError(f"Golden manifest missing: {_GOLDEN_MANIFEST}")

    docs = list(yaml.safe_load_all(_GOLDEN_MANIFEST.read_text()))

    shell_containers = {}
    cred_proxy_containers = {}
    gateway_containers = {}
    gateway_init_containers = {}
    pvc_count = 0
    storage_bytes = 0

    for doc in docs:
        if not doc or not isinstance(doc, dict):
            continue
        kind = doc.get("kind")
        name = (doc.get("metadata") or {}).get("name")
        spec = _pod_spec(doc)

        if kind == _KIND_PVC:
            # Standalone claims: one object each, and they do not scale with replicas.
            pvc_count += 1
            storage_bytes += _claim_storage(doc)
            continue

        if kind == _KIND_STATEFULSET and name == _SHELL_WORKLOAD:
            shell_containers = {c.get("name"): c for c in spec.get("containers", [])}
        elif kind == _KIND_DEPLOYMENT and name == _CRED_PROXY_WORKLOAD:
            cred_proxy_containers = {c.get("name"): c for c in spec.get("containers", [])}
        elif kind == _KIND_DEPLOYMENT and name == _GATEWAY_WORKLOAD:
            gateway_containers = {c.get("name"): c for c in spec.get("containers", [])}
            gateway_init_containers = {
                c.get("name"): c for c in spec.get("initContainers", [])
            }

        if kind == _KIND_STATEFULSET:
            # A StatefulSet's volumeClaimTemplates become one claim per replica.
            replicas = (doc.get("spec") or {}).get("replicas")
            replicas = 1 if replicas is None else int(replicas)
            for claim in (doc.get("spec") or {}).get("volumeClaimTemplates") or []:
                pvc_count += replicas
                storage_bytes += _claim_storage(claim) * replicas

    required = [
        (shell_containers, _SHELL_CONTAINER, _SHELL_WORKLOAD),
        (cred_proxy_containers, _CRED_PROXY_CONTAINER, _CRED_PROXY_WORKLOAD),
        (gateway_containers, _AGENT_CONTAINER, _GATEWAY_WORKLOAD),
        (gateway_containers, _DASHBOARD_CONTAINER, _GATEWAY_WORKLOAD),
        (gateway_containers, _FLUENT_BIT_CONTAINER, _GATEWAY_WORKLOAD),
        (gateway_init_containers, _AGENT_API_AUTH_CONTAINER, _GATEWAY_WORKLOAD),
    ]
    for containers, container_name, workload in required:
        if container_name not in containers:
            raise ValueError(
                f"container {container_name!r} not found in {workload} in the golden"
            )

    # The agent pod's base is everything always present: the agent, its log shipper, and the
    # agent-api-auth native sidecar (declared as an init container with restartPolicy:
    # Always, so it counts toward the pod's request like a regular container).
    agent_pod_base = [
        gateway_containers[_AGENT_CONTAINER],
        gateway_containers[_FLUENT_BIT_CONTAINER],
        gateway_init_containers[_AGENT_API_AUTH_CONTAINER],
    ]

    return {
        "operatorRendered": {
            "agentPod": {
                # One pod for the base. The dashboard is another container in that same pod,
                # so it adds resources but no pod.
                "base": _workload_entry(agent_pod_base, pods=1),
                "dashboard": _workload_entry(
                    [gateway_containers[_DASHBOARD_CONTAINER]], pods=0
                ),
            },
            "shellSandbox": _workload_entry([shell_containers[_SHELL_CONTAINER]], pods=1),
            "credentialProxy": _workload_entry(
                [cred_proxy_containers[_CRED_PROXY_CONTAINER]], pods=1
            ),
            # Claims are release-scoped rather than per-agent-replica: scaling the agent does
            # not create more of them, so the preflight must not multiply these.
            "storage": {
                "persistentVolumeClaims": pvc_count,
                "storageRequest": format_bytes(storage_bytes),
                "storageBytesRequest": storage_bytes,
            },
        }
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check for drift without writing")
    args = parser.parse_args()

    try:
        data = extract_footprint()
    except (FileNotFoundError, ValueError, yaml.YAMLError) as err:
        # Not drift: the check could not be performed at all, and the fix is a different one.
        print(f"ERROR: cannot build the chart footprint: {err}", file=sys.stderr)
        sys.exit(_EXIT_CANNOT_RUN)

    content = _HEADER + yaml.dump(data, sort_keys=False)

    if args.check:
        if not _FOOTPRINT_FILE.is_file():
            print(
                f"ERROR: {_FOOTPRINT_FILE} does not exist (run 'make chart-sync')",
                file=sys.stderr,
            )
            sys.exit(_EXIT_DRIFT)
        if _FOOTPRINT_FILE.read_text() != content:
            print(
                f"ERROR: {_FOOTPRINT_FILE} is out of date vs {_GOLDEN_MANIFEST}",
                file=sys.stderr,
            )
            sys.exit(_EXIT_DRIFT)
        print("Chart footprint is in sync with the operator golden.")
    else:
        _FOOTPRINT_FILE.write_text(content)
        print(f"Generated {_FOOTPRINT_FILE} from {_GOLDEN_MANIFEST}")


if __name__ == "__main__":
    main()
