apiVersion: agent.platform.io/v1alpha1
kind: PlatformAgent
metadata:
  name: platform-agent-gateway
  namespace: platform-agent
spec:
  projectId: "mplakhtiy-gke-dev"
  imageUri: "us-central1-docker.pkg.dev/mplakhtiy-gke-dev/platform-agent-repo/platform-agent:latest"
  chatTopicName: "platform-agent-chat-events"
  chatSubName: "platform-agent-chat-events-sub"
  gsaName: "platform-agent-chat-bot"
  ksaName: "platform-agent-chat-bot"
  googleChatAllowedUsers: "mplakhtiy@google.com"
  googleChatHomeChannel: "spaces/7K3-JyAAAAE"
  numericProjectId: "123456789012"
  clusterName: "platform-agent-cluster"
  location: "us-central1-c"
